"""PR table

Revision ID: 104052aa86f0
Revises: 
Create Date: 2021-11-09 22:13:51.338099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104052aa86f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'MERGED', name='prstatus'), nullable=True),
    sa.Column('base_branch', sa.String(length=200), nullable=True),
    sa.Column('compare_branch', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PR_author'), 'PR', ['author'], unique=True)
    op.create_index(op.f('ix_PR_title'), 'PR', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PR_title'), table_name='PR')
    op.drop_index(op.f('ix_PR_author'), table_name='PR')
    op.drop_table('PR')
    # ### end Alembic commands ###
