"""empty message

Revision ID: b4e2f7e3a04c
Revises: 104052aa86f0
Create Date: 2021-11-12 01:30:31.612455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e2f7e3a04c'
down_revision = '104052aa86f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_PR_author', table_name='PR')
    op.create_index(op.f('ix_PR_author'), 'PR', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PR_author'), table_name='PR')
    op.create_index('ix_PR_author', 'PR', ['author'], unique=False)
    # ### end Alembic commands ###
